### ISSUE TITLE
set_all method not working

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/rgbmatrix5x5-python#3]
Title says it all...

**Comment by Gadgetoid** [comment]
Should be fixed in https://github.com/pimoroni/rgbmatrix5x5-python/commit/e37c839299f72af6326dd85c982cc546b328306d

Have also added a test for this in future.

**Comment by Gadgetoid** [comment]
Could you grab the pre-release and verify it's fixed?

`sudo pip install -i https://test.pypi.org/simple/ rgbmatrix5x5`
